version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: sgccd
      DB_USERNAME: root
      DB_PASSWORD: mypass

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sgccd
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: mypass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
